---
title: "Cleaning Tree Density Seedling Data"
author: "Camila Vargas"
date: "1/27/2022"
output: html_document
---

## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Load packages
library(here)
library(tidyverse)
library(janitor)
library(readxl)
library(freeR)

## Sets R not to use scientific notations
options(scipen=999) 

```

## Exploring data
```{r}

excel_sheets(here::here("6.raw_data/Tree Density _ Seedling Density.xlsx"))

```

Just the one sheet we need.

## Read data
```{r}
tree_dens_raw <- read_excel(here::here("6.raw_data/Tree Density _ Seedling Density.xlsx")) %>% 
  clean_names()
```


## QA/QC

```{r}
colnames(tree_dens_raw)
str(tree_dens_raw)

unique(tree_dens_raw$study_species)
## Divide into species and phase?

complete(tree_dens_raw)

```

## Final data
```{r}
clean_tre_dens <- tree_dens_raw %>% 
  separate(col = "study_species",
           into = c("tree_type", "phase"),
           sep = " ")
```


## Save

```{r}
write_csv(clean_tre_dens, here::here("7.clean_data/Palmyra_Tree_Seedlings_DensityXXXX.csv"))
```



